### ISSUE TITLE
[proposal] integrate a package manager into eggs.

### ISSUE THREAD

**Issue by maximousblk** [nestlandofficial/nest.land#104]
#### Inspiration

I came across [Trex](https://github.com/crewdevio/Trex) and was wondering if nest could have a similar implementation natively.
As nest is already a growing registry for deno package it would be great to have a package manager accompanying this registry.

## Pitch

One thing we can all agree on is we don't want another npm. And for that the package manager should not do anything which makes it a necessity to run the project. It should be completely optional and users should be able to run and develop their applications without it at any point of the development and after deployment.

With that in mind, here is the concept:

what the package manager would do is something similar to npm but not limit the registry to nest. you could import from anywhere using a url which would work similar to `deno install` as it would get the name from the url.

what that would do is add an export to the `deps.ts` file which you can import in your source code. and if the package (egg?) is being used from nest, you would have ability to upgrade the versions, otherwise you would do it manually which is easy too.

expected commands:

```sh
eggs add package_name # would use nest

eggs add package_name -v 1.2.0 # would use nest and a specific version

eggs add https://url/to/package # install from provided source (auto naming)

eggs add -n package_name https://url/to/package # install from provided source (explicit naming)

eggs update package_name # update to a new stable version of the package (nest only)

eggs update package_name --unstable # update to the newest unstable version of the package (nest only)

eggs update package_name -v 1.2.4 # use a specific version (nest only)
```

### Feature that would be icing on the cake :cake:

- `eggs audit` - Deno seriously needs an `npm audit` feature. though this would need some changes in nest.land ([my sketchy implementation](https://github.com/maximousblk/audit))
- ability to add more registries (similar to PPAs in ubuntu) as this would make it easy to manage and audit "non nest" packages.
- change the name to nest and the packages would be called eggs :stuck_out_tongue_winking_eye:

**Comment by oganexon** [comment]
```bash
eggs update package_name # update to a new stable version of the package (nest only)

eggs update package_name --unstable # update to the newest unstable version of the package (nest only)

eggs update package_name -v 1.2.4 # use a specific version (nest only)
```

This part is already in progress ;)

```ts
import * as colors from "https://deno.land/std@v0.55.0/fmt/colors.ts";
import * as bcrypt from "https://deno.land/x/bcrypt@v0.2.0/mod.ts"
import * as eggs from "https://x.nest.land/eggs@v0.1.0/mod.ts"
import * as http from "https://deno.land/std/http/mod.ts"
```
![image](https://user-images.githubusercontent.com/52361520/85200588-0644e280-b2f9-11ea-91fc-267f9cb35e46.png)

**Comment by tbaumer22** [comment]
This is a great idea. I like the idea of working with deps.ts to keep things organized, though it may become controversial. At this point in time, I don't see an easy solution to this other than scanning the user's entire project for import statements.

I think that your `eggs audit` idea would be golden, and I have an idea for something we could add on top of that. Let's say that a package is hosted on both nest.land and deno.land/x. If you were to run `eggs audit`, we could check this and warn the user that a package has a potential vulnerability of not being immutable because they are using deno.land/x instead of nest.land. If this were the case, we could prompt them asking if they'd like us to switch to the immutable solution - nest.land.

Either way, I do think that these commands should keep compatibility with other registries because our goal is not to create a monopoly like NPM.

Regarding the name: You can ask @zorbyte why he didn't do this in the first place. I have yet to find a reason myself... 😄

**Comment by oganexon** [comment]
I think the add command is really secondary, it was a necessity for node but for deno it's superfluous. Adding a module only takes a copy and paste

Typing `eggs add https://deno.land/x/bcrypt@v0.2.0/mod.ts`
Or `import * from "https://deno.land/x/bcrypt@v0.2.0/mod.ts"` is the same

@maximousblk I'm missing something.

**Comment by maximousblk** [comment]
> I think the add command is really secondary, it was a necessity for node but for deno it's superfluous. Adding a module only takes a copy and paste - @oganexon 

while that is true, doing `eggs add bcrypt, fs, colors, https` is easier that copy and pasting each URL from their documentation page or typing it out.

main feature of the package manager would be upgrading the dependencies and hopefully auditing.

**Comment by oganexon** [comment]
Ok then 😉 
Upgrading the dependencies comes with the next release. (even if the command was there before, it has been improved)

**Comment by oganexon** [comment]
With recent events, should this proposal be closed?

**Comment by maximousblk** [comment]
@oganexon yes
