### ISSUE TITLE
[FEATURE] Automate testing for the CLI

### ISSUE THREAD

**Issue by tbaumer22** [nestlandofficial/nest.land#112]
**Describe the solution you'd like**
For scalability, we need to develop and automate the testing process for new features or fixes added in the CLI. The testing would be done on a command-by-command basis, and any new commands added will need to add and pass his/her/their tests.

To do this, we need to create a GitHub Actions workflow for this purpose, in addition to adding necessary test files in the `test` directory. See @ebebbington's example in the update command [here](https://github.com/nestlandofficial/nest.land/tree/master/eggs/tests)

This will also greatly improve the efficiency of reviewing and accepting PRs for new versions.

**Comment by divy-work** [comment]
@tbaumer22 I'll be interested in implementing this. (For testing the `publish` we could have a sample unlisted package.)

**Comment by tbaumer22** [comment]
@divy-work sounds good to me, thanks mate! For future reference, we'll want to target the `deploy` branch for this.

**Comment by divy-work** [comment]
@tbaumer22 Adding tests for `init` will not be possible since it needs user input. Other commands have been covered in #117
