### ISSUE TITLE
[FEATURE] Auto-formatting option on publish command

### ISSUE THREAD

**Issue by MartonDev** [nestlandofficial/nest.land#113]
**Is your feature request related to a problem? If so, please describe.**
If you want to follow the Deno philosophy, you need to format your code. Typing two separate commands to format and publish can be annoying. 

**Describe the solution you'd like**
Add an option to the config that allows users to auto-format, when running the publish command. `Eggs` would first execute `deno fmt` before publishing.
This could be done either on all files, or on only the ones that are in the `files` field (or the ones that are not in .eggsignore in the future).

**Comment by tbaumer22** [comment]
This is a great idea. Would the format option only format files included in `egg.json` though?

**Comment by MartonDev** [comment]
Yes that is what I don't know, but probably only the files included in egg.json, because the others don't get published anyways, so why formate
