### ISSUE TITLE
[FEATURE] Testimonial section

### ISSUE THREAD

**Issue by tbaumer22** [nestlandofficial/nest.land#120]
**Describe the solution you'd like**
A testimonial section on the homepage would be beneficial for users to see who recommends nest.land. Note: The users we feature here would not be random users; it would feature people prominent for something.

**Additional context**
@maximousblk suggested something similar to this:
![image](https://user-images.githubusercontent.com/20846869/85296098-df102180-b46e-11ea-9330-bec74d2b6f29.png)

**Comment by tbaumer22** [comment]
I'll plan to work on this when I get the opportunity, unless somebody else would like to do this.

**Comment by MartonDev** [comment]
If you don't have time, I'll work on it just let me know

**Comment by tbaumer22** [comment]
It may be this weekend when I get to it because I'm working this week. If you think you can get it done before then, feel free.

**Comment by tbaumer22** [comment]
Implemented in #169.
