### ISSUE TITLE
[BUG] eggs init: generates yaml when setting format is json

### ISSUE THREAD

**Issue by oganexon** [nestlandofficial/nest.land#127]
**Describe the bug**
When I enter "json" with the init command it generates yaml

**Expected behavior**
Even if the file extension is json, the file content isn't

**Screenshots**
![json](https://user-images.githubusercontent.com/52361520/85431991-95186000-b582-11ea-96a3-ffbbafc8975d.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - nest.land Version 0.1.4

**Additional feature request:**
When asking for config format, it should display which formats are supported

**Comment by divy-work** [comment]
@oganexon Definitely a bug. Will come up with a fix today.

**Comment by divy-work** [comment]
Including fix in #117
