### ISSUE TITLE
[info] README diagram does not properly reflect function of X

### ISSUE THREAD

**Issue by zorbyte** [nestlandofficial/nest.land#131]
The mediator represented on the diagram should be labelled as X, which has the core constituents API and CDN.

**Comment by zorbyte** [comment]
Also, GraphQL should be for MVP 3. We should discuss this later though.

**Comment by tbaumer22** [comment]
CC @maximousblk

**Comment by maximousblk** [comment]
Is this correct?

![image](https://user-images.githubusercontent.com/28438021/85772419-7361d900-b73a-11ea-82a7-482b9d6c57c7.png)
