### ISSUE TITLE
[BUG] Badge link broken, minor.

### ISSUE THREAD

**Issue by divy-work** [nestlandofficial/nest.land#133]
**Describe the bug**
The nest.land badge links to a 404 page.

**To Reproduce**
1) Go to https://github.com/divy-work/autopilot-deno
2) Click on the nest.land badge
3) And you have a 404

**Expected behavior**
Should go to https://nest.land/packages/autopilot

**Additional context**
The fix: remove the versioned url i.e.
`https://nest.land/packages/autopilot@0.1.7`

**Comment by divy-work** [comment]
The issue is because the CLI gives the badge with the broken link.

**Comment by tbaumer22** [comment]
We should patch this for our next release later today. It shouldn't be too difficult. I'll fix it.
