### ISSUE TITLE
[BUG] Website freezes after leaving a form blank.

### ISSUE THREAD

**Issue by CoolDeveloper101** [nestlandofficial/nest.land#134]
**Describe the bug**
In the [getting started](https://nest.land/#start) section, when someone leaves the username and password fields blank, the application freezes for some time and then shows the error **502 bad gateway**

**To Reproduce**
Go to https://nest.land/#start. Leave the username and password section blank. Click the fetch your api key button.

**Expected behavior**
To fetch the api key for an existing user.

**Screenshots**
![image](https://user-images.githubusercontent.com/49064764/85660067-cdc74f00-b6d2-11ea-982e-61bb97c25916.png)

**Comment by tbaumer22** [comment]
Thanks so much for creating this issue! That will be an easy fix on my end. I'll see if I have time to fix this in a few hours. For now, you can refresh the page if you're trying to log in or create an account.

Sorry for the inconvenience!
