### ISSUE TITLE
[BUG] Deno 1.1.2 error installation of eggs

### ISSUE THREAD

**Issue by RivierGrullon** [nestlandofficial/nest.land#144]
A few changes in the standard library are affecting the CLI. 

error: TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
  return Deno.dir("home") || "/";

**Comment by divy-work** [comment]
@RivierGrullon https://github.com/nestlandofficial/nest.land/pull/145 Will fix this issue. If don't want to wait for it to be merged, you can install the cli via the fork's branch.
