### ISSUE TITLE
[BUG] Eggs Publish Link 404s 

### ISSUE THREAD

**Issue by RobDWaller** [nestlandofficial/nest.land#155]
**Describe the bug**
When you run `eggs publish` it generates the following output:
```shell
You can now find your package on our registry at https://nest.land/package/resulty@0.3.0
```
The link `https://nest.land/package/resulty@0.3.0` will 404.

**To Reproduce**
Run `eggs publish`.

**Expected behavior**
The link generated by the `eggs publish` command should resolve, AKA return 200. 

**Screenshots**
![eggs-publish-cli-error](https://user-images.githubusercontent.com/634080/85946583-429dc180-b93d-11ea-805a-a3f27c586401.PNG)
![nest404](https://user-images.githubusercontent.com/634080/85946584-43365800-b93d-11ea-97da-6f9379b0d11c.PNG)

**Desktop (please complete the following information):**
 - OS: Docker Ubuntu 18.04
 - nest.land Version 0.1.2

**Smartphone (please complete the following information):**
 - Desktop

**Comment by divy-work** [comment]
@RobDWaller Similar issue at #133

**Comment by RobDWaller** [comment]
Well should the link `https://nest.land/package/resulty@0.3.0` resolve?

Also I ran `eggs upgrade` but still get `0.1.2` when I run `eggs -V`, I'm assuming `0.1.2` is the latest version?

**Comment by tbaumer22** [comment]
@RobDWaller I'm really sorry to hear that. This is a bug with `eggs upgrade`. The latest version of eggs is 0.1.5/0.1.6 (they are identical). Try installing it with this: `deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.1.5/mod.ts`

This should fix your original publish link 404 issue as well.
