### ISSUE TITLE
[FEATURE] Option to use latest version of a module

### ISSUE THREAD

**Issue by maximousblk** [nestlandofficial/nest.land#157]
**Is your feature request related to a problem? If so, please describe.**

Sometimes using the most recent version of a module is a requirement. But to do so under the current system is only possible by using the api, which is not possible in all cases

**Describe the solution you'd like**

make the latest version available through `https://x.nest.land/package_name@master` or `https://x.nest.land/eggs`

**Describe alternatives you've considered**

currently, the solution would be to fetch the latest version through the API and export it from `deps.ts` and import where needed. but that should not be the case.

**Additional context**

This would prevent manually updating the eggs version in the est CIs

**Comment by oganexon** [comment]
Since I suppose it's simply a matter of getting the most recent version, I propose to fix the problem for the API as well
latestVersion should return the greatest semver instead of the most recent version

See https://x.nest.land/api/package/Mandarine.TS

**Comment by tbaumer22** [comment]
We purposely didn't implement this because implicit versioning is a massive reason for peoples' code breaking over time. Thanks for the idea though!
