### ISSUE TITLE
[BUG] Blink "Unable to find any packages" after loading

### ISSUE THREAD

**Issue by yg** [nestlandofficial/nest.land#163]
**Describe the bug**

In the gallery, we can see a blinking error "Unable to find any packages" after loading

**To Reproduce**

1. Open https://nest.land/gallery
2. Reload it

**Expected behavior**

Should display all packages after loading

**Screenshots**

https://www.loom.com/share/3225ee666c4c415ebd11f96aaf23a812

**Desktop (please complete the following information):**

 - OS: Ubuntu

**Comment by tbaumer22** [comment]
Thanks for making this issue! This is already something we have in #105, so I'll close this one.
