### ISSUE TITLE
[BUG] Stop loading when loading fails

### ISSUE THREAD

**Issue by yg** [nestlandofficial/nest.land#167]
**Describe the bug**

Stop loading when loading fails

**To Reproduce**

1. Go to http://localhost:8080/#start
2. Fill all the details
3. Click the button
4. If it fails it keeps loading

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/61746440/86000454-32fca680-ba2b-11ea-9538-17e2e7f67e53.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu

**Comment by tbaumer22** [comment]
This shouldn't be a difficult issue to fix. I'll add that to my todos.

**Comment by yg** [comment]
@tbaumer22 I will work on this!
