### ISSUE TITLE
Website UX and styling fixes

### ISSUE THREAD

**Issue by zorbyte** [nestlandofficial/nest.land#55]
Checklist:
 - [x] Make links underlined and slightly bolder.
 - [ ] Use separate pages for docs and FAQ, or integrate them both into a docs page.
       Example: ![Boundary-supply-FAQ-1-1160x688](https://user-images.githubusercontent.com/39759284/84558371-d1271600-ad75-11ea-8607-62cb80d287a6.png)

**Comment by MartonDev** [comment]
Will start working on this
