### ISSUE TITLE
Including some files with /* result in `[ERROR:publish] Something broke... ` + images don't show up

### ISSUE THREAD

**Issue by oganexon** [nestlandofficial/nest.land#58]
Hi, just published my first module https://nest.land/package/remove-forever

My config file is the following:
```json
{
  "name": "remove-forever",
  "description": "Data erasure solution for files on deno 🦕",
  "stable": true,
  "version": "0.1.4",
  "files": [
    "README.md",
    "images/*",
    "mod.ts",
    "cli.ts",
    "lib/*"
  ]
}
```

Adding `images/*` throws an error but not with `lib/*`.
![image](https://user-images.githubusercontent.com/52361520/84577196-854a9000-adba-11ea-8c6c-e490fd6442c4.png)

Github: https://github.com/oganexon/deno-remove-forever

And images don't show on the nest page but I believe it is being worked on

[EDIT]: That's strange: `images/cli.gif` fails, not with `images/logo.png` but fails with `images/*` when there is only images/logo.png inside

Looks to be an issue on the server side, not the CLI:
```js
Response {
  _bodySource: ReadableStream { locked: false },
  contentType: "text/plain; charset=utf-8",
  _stream: null,
  url: "https://x.nest.land/api/piece",
  statusText: "Internal Server Error",
  status: 500,
  headers: Headers { server: nginx/1.14.0 (Ubuntu), date: Sat, 13 Jun 2020 19:34:31 GMT, content-type: text/plain; charset=utf-8, content-length: 21, connection: keep-alive, etag: W/"15-/6VXivhc2MKdLfIkLcUE47K6aH0" },
  redirected: false,
  type: "default"
}
```

**Comment by justablob** [comment]
Hey! Thank you for reporting this issue. We looked into it and it turns out that this is caused by a limit on one of our database columns which we forgot to adjust to fit production mode. I have modified the affected columns to support the larger data which is stored in production.
