### ISSUE TITLE
[FEATURE] CLI test publishing

### ISSUE THREAD

**Issue by tbaumer22** [nestlandofficial/nest.land#65]
**Is your feature request related to a problem? If so, please describe.**
In order for users to test their packages with the CLI, they currently have to publish legitimate versions of their package to the registry. This is an issue, as it can be confusing to both the developer and the user. In addition, a *test* version of a package could be unstable

**Describe the solution you'd like**
Add support for --dev in the publish command of the CLI to publish to a development version of a package

**Comment by justablob** [comment]
Could you maybe describe what this would be used for, because i'm not quite getting it. Would it "pretend" to publish a package but never actually do it?

**Comment by tbaumer22** [comment]
Added the unlisted feature in `0.1.3`. Closing this issue now, as it allows for this functionality.
