### ISSUE TITLE
[FEATURE] Reserved package names for testing purposes

### ISSUE THREAD

**Issue by oganexon** [nestlandofficial/nest.land#70]
**Is your feature request related to a problem? If so, please describe.**
If someone in the team wants to publish a package for testing purposes, everyone will see it in the gallery.
This is not the same issue as #65, here we want to publish a package and not test the publishing feature.

**Describe the solution you'd like**
Reserved package names like `eggs-testing-package-56` or random string that nobody else want to use.
They won't show up in the gallery, they are still accessible trough a link but not directly visible to the public.

**Describe alternatives you've considered**
Using random string but it pollutes the gallery.

**Comment by justablob** [comment]
How about unlisted packages, would that be a valid alternative?

**Comment by oganexon** [comment]
It's equivalent, you just have to be able to access them on the website.

**Comment by justablob** [comment]
Okay, i think we should work on this. I'll look into this a little more tomorrow.

**Comment by tbaumer22** [comment]
Implemented unlisted packages that do not display in gallery in `0.1.3`.
