### ISSUE TITLE
[BUG] Latest package version may not actually be the newest

### ISSUE THREAD

**Issue by tbaumer22** [nestlandofficial/nest.land#76]
**Describe the bug**
As experienced in the Mandarine.ts framework, the "latest" version appeared on the site as `1.0.1`, while the actual latest version in semver format is `1.1.0`.

**To Reproduce**
Visit [Mandarine.ts on nest.land](https://nest.land/package/Mandarine.TS)

**Expected behavior**
The expected behavior would be `1.1.0` appearing as the latest version on the site.

**Desktop (please complete the following information):**
 - nest.land Version: 0.1.0

**Comment by justablob** [comment]
So we'd just have to add a check to the CLI to see if the current version is younger than all other versions. Won't be too hard.

**Comment by tbaumer22** [comment]
@justablob or I could just do a sort on the frontend to determine this. The order of the array returns backwards anyway, so the field to select a version is the wrong order, which I am already planning to fix.

**Comment by oganexon** [comment]
Has this issue been fixed in the backend?

Because with the `/package` endpoint it still gives the wrong version
```ts
const res = await fetch("https://x.nest.land/api/package/Mandarine.TS");
const json = await res.json();
console.log(json.latestVersion.split("@")[1]) // 0.2.0
```
