### ISSUE TITLE
[FEATURE] `eggs upgrade` to upgrade to the latest verison of eggs cli

### ISSUE THREAD

**Issue by divy-work** [nestlandofficial/nest.land#78]
**Is your feature request related to a problem? If so, please describe.**
N/A

**Describe the solution you'd like**
```sh
deno install --unstable --A -f -n eggs <install-path>
```
Notice the `-f` to force install the new version. 

**Describe alternatives you've considered**
N/A

**Additional context**
Simply run the above command as Deno.run. Could I be assigned to this?

**Comment by tbaumer22** [comment]
@divy-work Sure, you’re welcome to work on this if you’d like.
