### ISSUE TITLE
[FEATURE] Fragment identifier to automatically choose version

### ISSUE THREAD

**Issue by andreespirela** [nestlandofficial/nest.land#85]
**Is your feature request related to a problem? If so, please describe.**
There should be the option to choose automatically & programmatically the version from the URL. So https://nest.land/package/Mandarine.TS#1.1.0 would automatically select 1.1.0 in the select box.

**Describe the solution you'd like**
Just some small javascript with any type of library or framework (jquery, react, angular...) to intercept if there's a hash in the hostname and then if there is apply it to the selectbox of the versions.

**Comment by tbaumer22** [comment]
This is a great idea. I'll try to find some time to work on implementing this for a future release!
