### ISSUE TITLE
[BUG] 504 Gateway Time-out

### ISSUE THREAD

**Issue by andreespirela** [nestlandofficial/nest.land#86]
**Describe the bug**
Error 504 Gateway Time-out is thrown when running app.

**To Reproduce**
```typescript
import { Controller, Service, GET, Session, MandarineCore } from "https://x.nest.land/Mandarine.TS@1.1.0/mod.ts";

new MandarineCore().MVC().run();
```

**Screenshots**
```
error: Import 'https://hw2qklfshsn3muak4xezh7rwib6raehrr5i4iszwuadxzw3llskq.arweave.net/PbUFLLI8m7ZQCuXJk_42QH0QEPGPUcRLNqAHfNtrXJU/mvc-framework/mandarineMVC.ts' failed: 504 Gateway Timeout
```
![Screen Shot 2020-06-16 at 9 20 30 PM](https://user-images.githubusercontent.com/60560109/84844051-84626a00-b017-11ea-8989-7d5da0c65177.png)

**Additional context**
When running a mandarine-powered application using the mandarine imports from nest.land, the blockchain provider `arweave` is throwing a 504 Gateway Time-out for several modules.

**Comment by tbaumer22** [comment]
Thanks for reaching out! Our discussion in Discord should fix your problem. I'm going to close this issue unless it persists after testing.

**Comment by tbaumer22** [comment]
For anyone having a similar issue, this is likely a problem with the files you include in your `egg.json` file. Make sure to double check your globbing string(s).
